/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgAdmin.java
 *
 * Created on 04 Des 13, 12:59:34
 */
package khanzahmsanjungan;

import component.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Kode
 */
public class DlgCetakAntrianFarmasi extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private String nama_instansi, alamat_instansi, kabupaten, propinsi,kontak,email;

    /** Creates new form DlgAdmin
     * @param parent
     * @param id */
    public DlgCetakAntrianFarmasi(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();
              
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new component.Panel();
        jPanel2 = new component.Panel();
        jLabel2 = new component.Label();
        jLabel6 = new component.Label();
        LblNama = new component.Label();
        jLabel8 = new component.Label();
        jLabel9 = new component.Label();
        LblNoRm = new component.Label();
        jLabel5 = new component.Label();
        jLabel7 = new component.Label();
        jLabel10 = new component.Label();
        jLabel11 = new component.Label();
        jLabel12 = new component.Label();
        jLabel13 = new component.Label();
        jLabel14 = new component.Label();
        jLabel15 = new component.Label();
        LblNoRw = new component.Label();
        LblAntrian = new component.Label();
        LblPoliklinik = new component.Label();
        LblDokter = new component.Label();
        btnCetak = new component.Button();
        btnKeluar = new component.Button();
        jPanel4 = new component.Panel();
        jLabel4 = new component.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 255)), "::[ Data Pasien ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(160, 130, 160))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 1));

        jPanel2.setPreferredSize(new java.awt.Dimension(390, 200));
        jPanel2.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("No Antrian Farmasi");
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 160, 160, 23);

        jLabel6.setForeground(new java.awt.Color(160, 110, 160));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText(":");
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(200, 160, 20, 23);

        LblNama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblNama.setText("Nama");
        LblNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblNama.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(LblNama);
        LblNama.setBounds(220, 40, 260, 23);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("No.RM");
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 15, 120, 23);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText(":");
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(jLabel9);
        jLabel9.setBounds(200, 10, 20, 23);

        LblNoRm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblNoRm.setText("Norm");
        LblNoRm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblNoRm.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(LblNoRm);
        LblNoRm.setBounds(220, 10, 240, 23);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Nama Pasien");
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 45, 120, 23);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Nomor Rawat");
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 70, 120, 23);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Poliklinik");
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 100, 120, 23);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Dokter");
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 130, 120, 23);

        jLabel12.setForeground(new java.awt.Color(160, 110, 160));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText(":");
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(jLabel12);
        jLabel12.setBounds(200, 40, 20, 23);

        jLabel13.setForeground(new java.awt.Color(160, 110, 160));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText(":");
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(jLabel13);
        jLabel13.setBounds(200, 70, 20, 23);

        jLabel14.setForeground(new java.awt.Color(160, 110, 160));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText(":");
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(jLabel14);
        jLabel14.setBounds(200, 100, 20, 23);

        jLabel15.setForeground(new java.awt.Color(160, 110, 160));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText(":");
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(jLabel15);
        jLabel15.setBounds(200, 130, 20, 23);

        LblNoRw.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblNoRw.setText("Norawat");
        LblNoRw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblNoRw.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(LblNoRw);
        LblNoRw.setBounds(220, 70, 240, 23);

        LblAntrian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblAntrian.setText("Antrian");
        LblAntrian.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblAntrian.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(LblAntrian);
        LblAntrian.setBounds(220, 160, 180, 23);

        LblPoliklinik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblPoliklinik.setText("Poliklinik");
        LblPoliklinik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblPoliklinik.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(LblPoliklinik);
        LblPoliklinik.setBounds(220, 100, 390, 23);

        LblDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblDokter.setText("Dokter");
        LblDokter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblDokter.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel2.add(LblDokter);
        LblDokter.setBounds(220, 130, 410, 23);

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/print.png"))); // NOI18N
        btnCetak.setMnemonic('K');
        btnCetak.setText("Cetak Antrian");
        btnCetak.setToolTipText("Alt+K");
        btnCetak.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnCetak.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCetak.setPreferredSize(new java.awt.Dimension(30, 30));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        btnCetak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCetakKeyPressed(evt);
            }
        });
        jPanel2.add(btnCetak);
        btnCetak.setBounds(470, 10, 160, 30);

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        btnKeluar.setMnemonic('K');
        btnKeluar.setText("Keluar");
        btnKeluar.setToolTipText("Alt+K");
        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKeluar.setPreferredSize(new java.awt.Dimension(30, 30));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        btnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeluarKeyPressed(evt);
            }
        });
        jPanel2.add(btnKeluar);
        btnKeluar.setBounds(470, 60, 160, 30);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(390, 51));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 9));

        jLabel4.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel4.add(jLabel4);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void btnCetakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCetakKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnKeluarActionPerformed(null);
        }
    }//GEN-LAST:event_btnCetakKeyPressed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
     this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Map<String, Object> param = new HashMap<>();
            try {
            ps=koneksi.prepareStatement("select nama_instansi, alamat_instansi, kabupaten, propinsi, aktifkan, wallpaper,kontak,email,logo from setting");
            rs=ps.executeQuery();
            while(rs.next()){                
                nama_instansi=rs.getString("nama_instansi");
                alamat_instansi=rs.getString("alamat_instansi");
                kabupaten=rs.getString("kabupaten");
                propinsi=rs.getString("propinsi");
                kontak=rs.getString("kontak");
                email=rs.getString("email");
            }
            } catch (SQLException e) {
              System.out.println(e);
            }
            param.put("namars",nama_instansi);
            param.put("alamatrs",alamat_instansi);
            param.put("kotars",kabupaten);
            param.put("propinsirs",propinsi);
            param.put("kontakrs",kontak);
            param.put("emailrs",email);
            param.put("antrian",LblAntrian.getText());
            param.put("norm",LblNoRm.getText());
            param.put("nama",LblNama.getText());
            param.put("norawat",LblNoRw.getText());
            param.put("poli",LblPoliklinik.getText());
            param.put("dokter",LblDokter.getText());
            param.put("logo",Sequel.cariGambar("select setting.logo from setting"));
            Valid.MyReportqry("rptAntrianFarmasi.jasper","report","::[ Bukti Register ]::",
                   "select reg_periksa.no_reg,reg_periksa.no_rawat,reg_periksa.tgl_registrasi,reg_periksa.jam_reg,"+
                   "reg_periksa.kd_dokter,dokter.nm_dokter,reg_periksa.no_rkm_medis,pasien.nm_pasien,pasien.jk,pasien.umur,poliklinik.nm_poli,"+
                   "reg_periksa.p_jawab,reg_periksa.almt_pj,reg_periksa.hubunganpj,reg_periksa.biaya_reg,reg_periksa.stts_daftar,penjab.png_jawab "+
                   "from reg_periksa inner join dokter inner join pasien inner join poliklinik inner join penjab "+
                   "on reg_periksa.kd_dokter=dokter.kd_dokter and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                   "and reg_periksa.kd_pj=penjab.kd_pj and reg_periksa.kd_poli=poliklinik.kd_poli where reg_periksa.no_rawat='"+LblNoRw.getText()+"' ",param);
            this.setCursor(Cursor.getDefaultCursor());
        dispose();
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnKeluarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCetakAntrianFarmasi dialog = new DlgCetakAntrianFarmasi(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Label LblAntrian;
    private component.Label LblDokter;
    private component.Label LblNama;
    private component.Label LblNoRm;
    private component.Label LblNoRw;
    private component.Label LblPoliklinik;
    private component.Button btnCetak;
    private component.Button btnKeluar;
    private component.Label jLabel10;
    private component.Label jLabel11;
    private component.Label jLabel12;
    private component.Label jLabel13;
    private component.Label jLabel14;
    private component.Label jLabel15;
    private component.Label jLabel2;
    private component.Label jLabel4;
    private component.Label jLabel5;
    private component.Label jLabel6;
    private component.Label jLabel7;
    private component.Label jLabel8;
    private component.Label jLabel9;
    private component.Panel jPanel1;
    private component.Panel jPanel2;
    private component.Panel jPanel4;
    // End of variables declaration//GEN-END:variables
       
    public void setPasien(String norawat){
        LblNoRw.setText(norawat);
        LblNoRm.setText(Sequel.cariIsi("select reg_periksa.no_rkm_medis from reg_periksa where reg_periksa.no_rawat=?", norawat));
        LblNama.setText(Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=?", LblNoRm.getText()));
        LblAntrian.setText(Sequel.cariIsi("select RIGHT(resep_obat.no_resep,4)as no_resep from resep_obat where resep_obat.no_rawat=?", norawat));
        LblPoliklinik.setText(Sequel.cariIsi("select nm_poli from poliklinik where kd_poli=?",Sequel.cariIsi("select kd_poli from reg_periksa where no_rawat=?", norawat)));
        LblDokter.setText(Sequel.cariIsi("select nm_dokter from dokter where kd_dokter=?",Sequel.cariIsi("select kd_dokter from reg_periksa where no_rawat=?", norawat)));
    }
}
